def calculate_score(semantic_sim: float, gemini_data: dict) -> dict:
    # Use the highly accurate ats_score generated by Gemini if available
    ai_score = gemini_data.get('ats_score', 0)
    
    # 30% Semantic Match (Holistic alignment)
    semantic = round(semantic_sim * 100)
    
    # Extract AI-driven sub-scores from new match_breakdown metadata
    breakdown = gemini_data.get('match_breakdown', {})
    
    skills = breakdown.get('skills_match', 0)
    experience = breakdown.get('experience_match', 0)
    keywords = breakdown.get('keyword_match', 0)

    # Use AI Score if valid, else calculate a composite
    if ai_score > 0:
        final_score = ai_score
    else:
        # Final ATS Composite Fallback Score
        final_score = round(
            semantic * 0.40 + 
            skills * 0.30 + 
            experience * 0.20 + 
            keywords * 0.10
        )

    return {
        'ats_score': max(0, min(100, final_score)),
        'semantic_score': semantic / 100,
        'skills_score': skills / 100,
        'experience_score': experience / 100,
        'formatting_score': 0.90 # Default assumption as it was removed from prompt
    }
